<?php

/**
 * Implements hook_theme().
 */
function singpost_content_collapsible_theme($existing, $type, $theme, $path){
	return [
		'paragraph__collapsible'           => [
			'base hook' => 'paragraph',
		],
		'paragraph__collapsible_nodes'     => [
			'base hook' => 'paragraph',
		],
		'paragraph__collapsible_text'      => [
			'base hook' => 'paragraph',
		],
		'paragraph__collapsible_paragraph' => [
			'base hook' => 'paragraph',
		]
	];
}