<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\search_api\IndexInterface;

/**
 * Implements hook_theme().
 */
function singpost_publications_theme($existing, $type, $theme, $path){
	return [
		'singpost_publications' => [
			'template'  => 'singpost-publications',
			'variables' => [
				'publications' => []
			]
		],
		'singpost_publication_single' => [
			'template'  => 'singpost-publication-single',
			'variables' => [
				'results' => []
			]
		]
	];
}

/**
 * Implements hook_search_api_index_items_alter().
 *
 * @param Drupal\search_api\IndexInterface $index
 * @param Drupal\search_api\Item\Item[] $items
 */
function singpost_publications_search_api_index_items_alter(IndexInterface $index, array &$items){
	$published_field = '';
	$fields          = $index->get('field_settings');
	foreach ($fields as $field => $field_data){
		if ($field_data['datasource_id'] == 'entity:singpost_publication' && strpos($field,
				'published') !== FALSE){
			$published_field = $field;
			break;
		}
	}

	if (!empty($published_field)){
		foreach ($items as $item_id => $item){
			if (strpos($item_id, 'entity:singpost_publication') !== FALSE){
				$is_published = $item->getField($published_field)->getValues();
				if (empty($is_published) || empty($is_published[0])){
					unset($items[$item_id]);
				}
			}
		}
	}
}


/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param $operation
 * @param \Drupal\Core\Session\AccountInterface $account
 *
 * @return \Drupal\Core\Access\AccessResultAllowed|\Drupal\Core\Access\AccessResultNeutral
 */
function singpost_publications_singpost_publication_access(
	EntityInterface $entity,
	$operation,
	AccountInterface $account){
	if ($operation == 'view'){
		return AccessResult::allowed();
	}

	return AccessResult::neutral();
}