<?php

/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 *
 * Implements hook_theme().
 */
function singpost_content_basic_paragraph_theme($existing, $type, $theme, $path){
	return [
		'paragraph__well'  => [
			'base hook' => 'paragraph',
		],
		'paragraph__modal' => [
			'base hook' => 'paragraph',
		]
	];
}

/**
 * Implements hook_theme_suggestions_alter().
 *
 * @param array $suggestions
 * @param array $variables
 * @param $hook
 */
function singpost_content_basic_paragraph_theme_suggestions_alter(
	array &$suggestions,
	array $variables,
	$hook){
	/**
	 * @var \Drupal\paragraphs\Entity\Paragraph $paragraph
	 */
	if(isset($variables['elements']['#paragraph'])){
		$paragraph = $variables['elements']['#paragraph'];
		$parent    = $paragraph->getParentEntity();
		if ($parent){
			$suggestions[] = 'paragraph__' . $parent->bundle() . '__' . $paragraph->bundle();
		}
	}
}