<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\Webform;

/**
 * Implements hook_theme().
 */
function singpost_content_bulk_mail_solutions_theme($existing, $type, $theme, $path){
	return [
		'table_domestic' => [
			'variables' => ['data' => []],
		],
		'table_international' => [
			'variables' => ['data' => []],
		],
		'non_bulk_mails' => [
			'variables' => ['data' => []],
		],
	];
}

/**
 * Implements hook_form_alter().
 */
function singpost_content_bulk_mail_solutions_form_alter(
	&$form,
	FormStateInterface $form_state,
	$form_id){
	if (isset($form['#webform_id'])){
		$config  = Drupal::config('singpost.webform.bulk_mail_solutions');
		$webform = $config->get('webform_id');

		if ($form['#webform_id'] == $webform){
			$webform  = Webform::load($webform);
			$elements = $webform->getElementsDecoded();

			$form['#attached']['library'][] = 'singpost_content_bulk_mail_solutions/form';

			$form['#attached']['drupalSettings']['singpost_content_bulk_mail_solutions']['webform_id'] = $elements['#attributes']['id'] ?: $form_id;
		}
	}
}